# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_specific_heat <- function(tau_vec, ent_vector, specific_heat, heat_peak_indices, tau_peak_values) {
    invisible(.Call('_infoCoRe_calculate_specific_heat', PACKAGE = 'infoCoRe', tau_vec, ent_vector, specific_heat, heat_peak_indices, tau_peak_values))
}

entropy <- function(mu, ent) {
    invisible(.Call('_infoCoRe_entropy', PACKAGE = 'infoCoRe', mu, ent))
}

net_operator <- function(lambda, mu, tau = 1) {
    invisible(.Call('_infoCoRe_net_operator', PACKAGE = 'infoCoRe', lambda, mu, tau))
}

entropy_matrix <- function(mu_matrix, ent_vector) {
    invisible(.Call('_infoCoRe_entropy_matrix', PACKAGE = 'infoCoRe', mu_matrix, ent_vector))
}

get_transition_tau <- function(lambda, mu_matrix, tau_vec) {
    invisible(.Call('_infoCoRe_get_transition_tau', PACKAGE = 'infoCoRe', lambda, mu_matrix, tau_vec))
}

get_eig <- function(x, eigval, eigvec, val_only = 0L, order = 1L) {
    invisible(.Call('_infoCoRe_get_eig', PACKAGE = 'infoCoRe', x, eigval, eigvec, val_only, order))
}

get_eig_cx <- function(x, eigval, eigvec, val_only = 0L, order = 1L) {
    invisible(.Call('_infoCoRe_get_eig_cx', PACKAGE = 'infoCoRe', x, eigval, eigvec, val_only, order))
}

laplacian <- function(Adj, norm = 1L) {
    .Call('_infoCoRe_laplacian', PACKAGE = 'infoCoRe', Adj, norm)
}

laplacian_cx <- function(Adj, weighted = 0L, norm = 1L) {
    .Call('_infoCoRe_laplacian_cx', PACKAGE = 'infoCoRe', Adj, weighted, norm)
}

driver <- function(Adj, weighted = 0L, directed = 0L, norm = 1L, val_only = 0L, order = 1L, custom_tau_vec = as.numeric( c(1.0, 10, 50, 100))) {
    .Call('_infoCoRe_driver', PACKAGE = 'infoCoRe', Adj, weighted, directed, norm, val_only, order, custom_tau_vec)
}

